apiVersion: v1
kind: Service
metadata:
  name: {{ include "qa-server-chart.fullname" . }}
  labels:
    {{- include "qa-server-chart.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: {{ .Values.service.restPort }}
      targetPort: rest
      protocol: TCP
    - name: graphql
      port: {{ .Values.service.gqlPort }}
      targetPort: graphql
      protocol: TCP
  selector:
    {{- include "qa-server-chart.selectorLabels" . | nindent 4 }}